[package]
name = "sacp-test"
version = "1.0.0-alpha"
edition = "2024"

[dependencies]
sacp = { path = "../sacp" }
sacp-proxy = { path = "../sacp-proxy" }
serde.workspace = true
futures.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
